### ISSUE TITLE
[RS09-01] Diseñar una Tab

### ISSUE THREAD

**Issue by elbraulio** [samhv/jedit_cc4401#21]
La tab será diseña en un ambiente aparte, y luego será añadida a un panel que administrará todas las tabs.

**Comment by elbraulio** [comment]
BufferSwitcher es la clase que contiene la barra que queremos cambiar
BufferSet es quien administra los Buffers y se le puede pedir uno según su index.

Al parecer:
 -Buffer es quien administra el editor de texto (textArea)
 -EditPane es quien administra el Buffer
 -BufferSet es quien se encarga de qué Buffer está "activo"
 -BufferSwitcher es la parte "visual" de BufferSet

**Comment by elbraulio** [comment]
Al parecer debemos solo cambiar BufferSwitcher y reemplazarlo por nuestro administrador de tabs.
Ademas extender JTabbedPane para poder organizar los buffers

**Comment by hfehrmann** [comment]
En vez de extender JTabbedPane se decidio implementar una Tab simple que cumpla con lo requerido, aun que faltan cosas que tienen relacion con el "Look" del Tab.

**Comment by hfehrmann** [comment]
Actualmente cierra los tabs. Falta overflow y mover los tabs

**Comment by hfehrmann** [comment]
Listo método de overflow. Falta poder mover los tabs.

**Comment by hfehrmann** [comment]
Mover tabs esta fuera de este requisito
