### ISSUE TITLE
[RS09-02] Crear en un panel que permita tener varias tabs

### ISSUE THREAD

**Issue by elbraulio** [samhv/jedit_cc4401#24]
Dentro de este panel se podrá mover, insertar y cerrar tabs.

**Comment by elbraulio** [comment]
Se usará JTabbedPane https://docs.oracle.com/javase/tutorial/uiswing/components/tabbedpane.html

**Comment by hfehrmann** [comment]
Quizas sea necesario cambiar un poco la estructura interna del display de los archivos si se decide utilizar esta clase.

**Comment by hfehrmann** [comment]
Se creo clase TabbedBufferedSwitcher,
