### ISSUE TITLE
[RS09-04] Permitir cerrar tabs en panel

### ISSUE THREAD

**Issue by elbraulio** [samhv/jedit_cc4401#27]
Se deben poder cerrar tabs sin interferir el comportamiento de las otras tabs

**Comment by hfehrmann** [comment]
jEdit provee esta funcionalidad, por lo que esta realizado en parte. Falta agregar un boton dentro del tab que emule lo que realiza jEdit

**Comment by hfehrmann** [comment]
Se agrego el botón cruz que permite cerra el tab
