### ISSUE TITLE
[RS09-07] Al seleccionar un tab debe cambiar el foco

### ISSUE THREAD

**Issue by elbraulio** [samhv/jedit_cc4401#31]
Esto no debe ser afectado por el cambio de posicion de las tabs

**Comment by hfehrmann** [comment]
este requisito ya se cumple

**Comment by hfehrmann** [comment]
Parcial, falta mostrar foco en tab

**Comment by hfehrmann** [comment]
El foco se pone sobre la tab al momento de abrir, y cuando se cierra y el tab siguiente esta fuera de foco
